[package]
name = "paynow"
version = "0.1.0"
authors = ["rushmorem"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
url = { version = "2", features = ["serde"] }
uuid = "0.8"
